### ISSUE TITLE
Problem install the website on step 3

### ISSUE THREAD

**Issue by msfraish** [huludini/aura-kingdom-web#6]
i have a problem on install the website
He says "Whoops, looks like something went wrong."
![2016_03_11_16_34_09](https://cloud.githubusercontent.com/assets/13107592/13753554/766371e6-ea24-11e5-923f-5b77e1fb0342.jpg)

**Comment by msfraish** [comment]
now the same problem but white page @@
up...

**Comment by tomirons** [comment]
Check the application logs (**storage/logs/laravel.log**)

Please don't copy and paste the whole thing.

**Comment by msfraish** [comment]
This is my log : 

```
 #4 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Connection.php(864): call_user_func(Object(Closure))
 #5 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Connection.php(732): Illuminate\Database\Connection->getPdo()
 #6 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Connection.php(621): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Connection.php(342): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(55): Illuminate\Database\Connection->select('select * from i...', Array)
#9 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(141): Illuminate\Database\Schema\Builder->hasTable('migrations')
#10 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(405): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#11 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(103): Illuminate\Database\Migrations\Migrator->repositoryExists()
#12 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(58): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 /var/www/html/aura-kingdom-web-master/bootstrap/cache/compiled.php(1232): call_user_func_array(Array, Array)
#15 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#16 /var/www/html/aura-kingdom-web-master/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/aura-kingdom-web-master/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/aura-kingdom-web-master/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/aura-kingdom-web-master/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/aura-kingdom-web-master/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
```

**Comment by tomirons** [comment]
That doesn't help me... all I need is the line before the stack trace.

**Comment by msfraish** [comment]
OK ,
[2016-03-15 23:15:56] production.ERROR: exception 'PDOException' with message 'SQLSTATE[08006] [7] FATAL:  Ident authentication failed for user "postgres"' in /var/www/html/aura-kingdom-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55

**Comment by tomirons** [comment]
I think that error explains its self... it seems that it can't connect to the database.

Try googling the error.

**Comment by msfraish** [comment]
now the problem is 
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "roles_name_unique"
DETAIL:  Key (name)=(admin) already exists. (SQL: insert into "roles" ("name", "display_name", "created_at", "updated_at") values (admin, Administrator, 2016-03-18 06:29:58, 2016-03-18 06:29:58))' in /var/www/master/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669

**Comment by msfraish** [comment]
this is real problem
Next exception 'ErrorException' with message 'file_put_contents(/var/www/web/storage/settings.json): failed to open stream: Permission denied (View: /var/www/web/resources/views/admin/install/settings.blade.php)' in /var/www/web/vendor/efriandika/laravel-settings/src/Cache.php:127
What is solution ?!!

**Comment by tomirons** [comment]
That isn't a problem, it's telling you that you haven't set the permissions.

**Comment by msfraish** [comment]
i used this permissions,
chmod -R 777 storage/app/
chmod -R 777 storage/framework/
chmod -R 777 storage/logs/
chmod -R 777 bootstrap/cache/
chmod -R 777 .env
any other permissions ?

**Comment by tomirons** [comment]
Just chmod the whole directory, then it should work.

**Comment by msfraish** [comment]
Thank you to the problem has been resolved
